language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN='4b15a883-d1cf-4b1e-99a0-4254b0c395dd'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - sestanovov@gmail.com
    on_success: never
    on_failure: always